import{S as v,i as d,a as b}from"./assets/vendor-f736e62a.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();function L(){const i=document.querySelector(".gallery");i.innerHTML=""}function g(i){const a=document.querySelector(".gallery");let l="";i.forEach(r=>{l+=`
      <a class="gallery__item" href="${r.largeImageURL}" target="_blank">
        <figure class="gallery__figure">
          <img class="gallery__img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
          <figcaption class="gallery__figcaption">
            <div class="gallery__caption">Likes: ${r.likes}</div>
            <div class="gallery__caption">Views: ${r.views}</div>
            <div class="gallery__caption">Comments: ${r.comments}</div>
            <div class="gallery__caption">Downloads: ${r.downloads}</div>
          </figcaption>
        </figure>
      </a>`}),a.innerHTML+=l}document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector("#search-form"),a=document.querySelector("#search-input"),l=document.querySelector(".gallery"),r=document.querySelector(".loader"),e=document.querySelector("#load-more-btn"),t=new v(".gallery a");let s=1,u="",y=0;async function f(n,o){try{return r.style.display="block",(await b.get("https://pixabay.com/api/",{params:{key:"43289261-b2f679df5fe28faf218337d96",q:n,image_type:"photo",orientation:"horizontal",captions:!0,page:o,per_page:15}})).data}catch{throw new Error("Failed to fetch images from Pixabay API")}finally{r.style.display="none"}}async function m(n){n.preventDefault();const o=a.value.trim();if(!o){d.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}L(),u=o,s=1,await p(u,s),l.style.display="flex"}async function p(n,o){try{const{hits:c,totalHits:_}=await f(n,o);g(c),t.refresh(),o===1&&(y=document.querySelector(".gallery__item").getBoundingClientRect().height),c.length===0||o*15>=_?(e.style.display="none",d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):e.style.display="block"}catch{d.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"}),e.style.display="none"}}async function h(){s++;const{hits:n}=await f(u,s);if(n.length===0){e.style.display="none",d.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}g(n),t.refresh();const o=y*2;window.scrollBy({top:o,behavior:"smooth"})}i.addEventListener("submit",m),e.addEventListener("click",h),e.style.display="none"});
//# sourceMappingURL=commonHelpers.js.map
