import{S as _,i as u,a as v}from"./assets/vendor-f736e62a.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&t(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function b(){const l=document.querySelector(".gallery");l.innerHTML=""}function L(l){const s=document.querySelector(".gallery");let i="";l.forEach(t=>{i+=`
      <a class="gallery__item" href="${t.largeImageURL}" target="_blank">
        <figure class="gallery__figure">
          <img class="gallery__img" src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
          <figcaption class="gallery__figcaption">
            <div class="gallery__caption">Likes: ${t.likes}</div>
            <div class="gallery__caption">Views: ${t.views}</div>
            <div class="gallery__caption">Comments: ${t.comments}</div>
            <div class="gallery__caption">Downloads: ${t.downloads}</div>
          </figcaption>
        </figure>
      </a>`}),s.innerHTML+=i}document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector("#search-form"),s=document.querySelector("#search-input"),i=document.querySelector(".gallery"),t=document.querySelector(".loader"),e=document.querySelector("#load-more-btn"),r=new _(".gallery a");let o=1,d="",y=0;async function m(n,a){try{return t.style.display="block",(await v.get("https://pixabay.com/api/",{params:{key:"43289261-b2f679df5fe28faf218337d96",q:n,image_type:"photo",orientation:"horizontal",captions:!0,page:a,per_page:15}})).data}catch{throw new Error("Failed to fetch images from Pixabay API")}finally{t.style.display="none"}}async function g(n){n.preventDefault();const a=s.value.trim();if(!a){u.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}b(),d=a,o=1,await f(d,o),i.style.display="flex",e.style.display="block",document.documentElement.style.scrollBehavior="smooth"}async function f(n,a){try{const{hits:c,totalHits:h}=await m(n,a);L(c),r.refresh(),a===1&&(y=document.querySelector(".gallery__item").getBoundingClientRect().height),(c.length===0||a*15>=h)&&(e.style.display="none",u.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{u.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}}async function p(){o++;const n=y*2;await f(d,o),window.scrollBy({top:n,behavior:"smooth"})}l.addEventListener("submit",g),e.addEventListener("click",p)});
//# sourceMappingURL=commonHelpers.js.map
